name: Client CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Check lint
        run: npm run lint

      - name: Build project
        run: npm run build